### ISSUE TITLE
Readme corrections

### ISSUE THREAD

**Issue by tekavec** [martinobordin/Chart.Mvc#1]
Hi Martino,

This is a very useful wrapper, thumbs up! I would only suggest you to correct one small mistake and add one information to your readme file:
- instead of ComplextDataset it should be ComplexDataset
- in the current version Chart.js must be included before the @Html.CreateChart call (perhaps it would be wise to use another js event so that Chart.js could be loaded at the end of the view)

Kind regards,
Tomaz

**Comment by martinobordin** [comment]
Done, thanks.
Actually you can call @Html.CreateChart at the end of the view, just be sure to include the Chart.JS before call it (maybe using MVC sections)
