### ISSUE TITLE
Type Clash between System.Web.Helpers.Chart and Chart.Mvc

### ISSUE THREAD

**Issue by cigano** [martinobordin/Chart.Mvc#13]
I installed Chart.Mvc and tried to use in a Razor View from my project. The Instellisense and IIS returned me the following error:

```
CS0426: Name type 'Mvc' does not exist in type 'System.Web.Helpers.Chart'
```

`System.Web.Helpers.Chart` comes from Microsoft.AspNet.WebPages package. I can't remove this package from my application because other Views use this package.

**Comment by martinobordin** [comment]
Try to use the global keyword. That forces the namespace resolution to start at the very top. 

 `global::Chart.Mvc;`

 http://msdn.microsoft.com/en-us/library/c3ay4x3d.aspx

**Comment by cigano** [comment]
Okay, worked so far, but [I made a fork and updated the name](https://github.com/cigano/ChartJs.Mvc) (ChartJs.Mvc) and some package stuff. Would you like to accept a pull request?

**Comment by martinobordin** [comment]
I will think about it, because pulling your request would break the current
projects

_Martino Bordin_
_IT Consultant - Software Architect_

_cell:_ +39 348 0136512
_skype:_ martino.bordin
_mail:_ info@martinobordin.it
_web:_ www.martinobordin.it

**Comment by martinobordin** [comment]
I'll think about it because pulling your request will break all the projects using this package..

**Comment by cigano** [comment]
You can release as version 2, explaining that this version will demand some code refactoring. 

I performed some tests with your version and mine and the replacements were minimal.

**Comment by martinobordin** [comment]
Let's wait for a moment, the namespace clash is not so common and not a real issue
