### ISSUE TITLE
show value above bars using asp.net mvc

### ISSUE THREAD

**Issue by aminsoraya** [martinobordin/Chart.Mvc#17]
hi
how can i use constent values in each of above bars like title which must be hovered that.
i am using asp.net mvc 5 and my code that is used is 

`    @{
        var globalbarChart = new BarChart();
        globalbarChart.ComplexData.Labels.AddRange(Model.Select(d => ShamsiDate.ChangeDate(d.Date_Submitted).ToString()).ToList());

```
    globalbarChart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
        {
            new ComplexDataset
            {
                Data =Model.Select(r=>double.Parse(r.Global_Rank.ToString())).ToList(),
                Label = "My First dataset",
                FillColor = "rgba(255,255,0,0.3)",
                StrokeColor = "rgba(255,0,255,0.3)",
                PointColor = "rgba(220,220,220,1)",
                PointStrokeColor = "#fff",
                PointHighlightFill = "#fff",
                PointHighlightStroke = "rgba(220,220,220,1)",

           }
                      });

}
<canvas id="globalCanvas" width="500" height="300"></canvas>`
```

**Comment by martinobordin** [comment]
Can you show me the code with plain chart.js configuration?

**Comment by aminsoraya** [comment]
hello mr martinobordin
i dont know your mean (chart.js)!
this is another part of codes:

`var globalbarChart = new BarChart();
globalbarChart.ComplexData.Labels.AddRange(Model.Select(d => 
ShamsiDate.ChangeDate(d.Date_Submitted).ToString()).ToList());
`

and a chart.j is installed from nugetPackage (current version is 1.0.0.2)

**Comment by martinobordin** [comment]
Yes but can you achieve what you want with chart.js directly?
Chart.Mvc is just a wrapper to that library, so first of all I would like to see a sample of what you're trying to get using only the js library.

**Comment by aminsoraya** [comment]
this is a good sample
[image is here](https://drive.google.com/file/d/0Bya6Hqi3nw68MFI3OTBWc01rcjg/view?usp=sharing)
I want 20,14,23 in this scenario

**Comment by martinobordin** [comment]
Cannot do that with chart.js

**Comment by aminsoraya** [comment]
oh sorry ! this is not image i mean . i mean(10,1,4,6,9,3), those is a correct value placement that i want . so how can i do that?

**Comment by martinobordin** [comment]
It's a function not supported by the js library itself, sorry..
