### ISSUE TITLE
Problem with Html.CreateChart

### ISSUE THREAD

**Issue by ghost** [martinobordin/Chart.Mvc#18]
![knipsel](https://cloud.githubusercontent.com/assets/17408736/16002691/323bc3d4-3159-11e6-8c6d-c9fcc3af7d1a.PNG)

This is the error: `HtmlHelper<PMSensorDetail>' does not contain a definition for 'CreateChart' and no extension method 'CreateChart' accepting a first argument of type 'HtmlHelper<PMSensorDetail>' could be found (are you missing a using directive or an assembly reference?)`

Does somebody have an idea?

**Comment by martinobordin** [comment]
Can you see this method in the object browser?

**Comment by ghost** [comment]
These are the methods in the object browser under the html topic
![knipsel](https://cloud.githubusercontent.com/assets/17408736/16005356/2b7ec466-3167-11e6-9913-36da55a39602.PNG)

**Comment by martinobordin** [comment]
You have to check under the Chart.Mvc.dll

**Comment by ghost** [comment]
Sorry! Hope this is what you need
![knipsel](https://cloud.githubusercontent.com/assets/17408736/16005790/6cbb6b1c-3169-11e6-8bf7-0b8da3da6634.PNG)

**Comment by martinobordin** [comment]
Yes. So actually there is an HtmlExtenions class..please be sure to import the required namespaces as in the sample

**Comment by ghost** [comment]
OMG! Such a stupid mistake! Thanks for helping me out!

**Comment by martinobordin** [comment]
No problem
