### ISSUE TITLE
GenerateLegend

### ISSUE THREAD

**Issue by tekavec** [martinobordin/Chart.Mvc#2]
Hi Martino,

I can't figure out how to show a legend with Chart.Mvc - I noted in the Chart.js documentation "generateLegend" can be used. Can you please advise, thank you.

Kind regards,
Tomaz

**Comment by martinobordin** [comment]
The generated chart object will be named like the canvas plus "_chart" suffix.

For example:

<canvas id="myCanvas" width="400" height="400"></canvas>

Your chart object will be named "myCanvas_chart", so you can just call myCanvas_chart.generateLegend() to obtain the legend

I just updated the readme to explain this behavior.

**Comment by tekavec** [comment]
Great! Thank you a lot.
