### ISSUE TITLE
unable to generate legend

### ISSUE THREAD

**Issue by mokarenlam** [martinobordin/Chart.Mvc#20]
Thx for Chart.Mvc, really like to be able to use this in MVC.  Could you post a simple example on how to show legend.  Much appreciated it.

**Comment by muehan** [comment]
need lables too

**Comment by martinobordin** [comment]
Something like this should works `myCanvas_chart.generateLegend()`

**Comment by muehan** [comment]
this does only return some HTML. Even if I add the HTML to a div all the classes from the template do not exist. It should be in the canvas, or not? is the label a 2.0 feature?

**Comment by andresfraile** [comment]
Not sure if it's the right place to post this, but I solved this issue by adding a div after my canvas:
`<div id="legend" class="row chart-legend"></div>`
and using Jquery to show the `generateLegend()` output.: `$('#legend').html(myCanvas_chart.generateLegend())`

**Comment by martinobordin** [comment]
Yes, it's exactly how to do it
