### ISSUE TITLE
Support for ASP.NET Core

### ISSUE THREAD

**Issue by th0masj0** [martinobordin/Chart.Mvc#25]
Hi,

I'm very interested in your solution for my current project. This will be developed in ASP.NET Core 1.0 with a modularized structure. Currently your solution contains some parts for Mvc6. Are there any plans to port this for ASP.NET Core inclusive missing options from Chart.Mvc like colors? Currently I'm missing some points for evaluation:
- Your Chart.Mvc6 uses netcoreapp1.0. This could be changed to netstandard(1.6) for integration in .NET Core libraries as well.
- A standalone publish to nuget for easily integration in ASP.NET Core solutions.

Thanks and Regards
Thomas

**Comment by martinobordin** [comment]
@leedale1981, since you worked on MVC6, could you work on this issue?

**Comment by leedale1981** [comment]
Hi Thomas,

I plan to implement some of the newer properties for the charts in the MVC 6 library and I plan to publish the library as a nuget package. I will also update the project.json to use the netstandard1.6 target.

This should be done fairly soon.

**Comment by th0masj0** [comment]
Hi,

thanks for your reply. Currently I'm switched to client side configuration and only passing correct json data to view. My reasons are:
- Many options of Chart.js 2 are missing currently.
- Lag of scatter chart support. Therefore LineChart data type must be changed from List<double> to List<object> for supporting doubles or {x,y}-objects. Also time handling with moment.js is important.

I will give the new version a try later. Thx

Regards
Thomas

**Comment by amkuchta** [comment]
Out of curiosity, is there any movement on this?  I see that the last update was in October...  I'd like to use the library in an application that I am building, but need it to work with MVC6 / ASP.NET Core (targeting .NET 4.5.2).  Additionally, are there plans to update to Chart.js 2?

**Comment by leedale1981** [comment]
I haven't been able to work on this recently due to work and other commitments. I'm happy to pick this up when I get time but I can't guarantee it will be anytime soon.

**Comment by martinobordin** [comment]
It won't be supported
