### ISSUE TITLE
Is it possible to create a continously updated Chart somehow?

### ISSUE THREAD

**Issue by SonicTTH** [martinobordin/Chart.Mvc#27]
Hello,

Is it possible to have some ajax function running on the website which calls for a new datapoint once in a while? How can I access the Data that the chart uses from javascript and make it update its view?

**Comment by martinobordin** [comment]
Take a look to jquert ajax() to retrieve html from the server and update a div content.
The html returned by the server should be a partial view that use html and chart.mvc to display the chart
