### ISSUE TITLE
CreateChart is not working.

### ISSUE THREAD

**Issue by Bodmoor** [martinobordin/Chart.Mvc#30]
![2016-10-21_17-08-57](https://cloud.githubusercontent.com/assets/18680317/19603214/976f2954-97b0-11e6-9d18-df70782609cc.png)
I get this error:

'IHtmlHelper<dynamic>' does not contain a definition for 'CreateChart' and the best extension method overload 'HtmlExtensions.CreateChart<BarChartOptions>(HtmlHelper, string, ComplexChartBase<BarChartOptions>)' requires a receiver of type 'HtmlHelper'

I am running from an asp.net core project using .NET 4.5.2. Using version 1.0.0.2 of Chart.Mvc and I've tried using chart.js version 2.0.2 and 1.0.1. Both gave me the same error.

I have included the chart.js reference like in the example in _Layout.cshtml: <script src="~/lib/chartjs/Chart.bundle.js"></script>

It seems like there is an overload missing? But more likely, I am missing something.

Unfortunately the object browser does not work well for this project type, but I do have the extensions included.

**Comment by martinobordin** [comment]
Hello. Asp.net core is not supported by the current Nuget package. 
It's support is under development and you can try it to use the current bits in github

**Comment by Bodmoor** [comment]
Thank you, I will try that. I'll also try to run the sample project 1:1 to see if there's a silly mistake in there somewhere.
