### ISSUE TITLE
White, clean sheet.

### ISSUE THREAD

**Issue by Jora-zolotoj** [martinobordin/Chart.Mvc#31]
1.   PM> Install-Package Chart.Mvc.
2.   Inserted into View all the code entirely from the example:

@{Layout = null;}
        @using Chart.Mvc.ComplexChart;
        @using Chart.Mvc.Extensions
        @....
...
        <canvas id="myCanvas" width="400" height="400"></canvas>
        @Html.CreateChart("myCanvas", barChart)
1.   Run...:

An unhandled exception on line 16, column 801 to http: // localhost: 62329 / Home / ComplexCharts
0x800a1391 - JavaScript Runtime Error: "Chart" is not defined

...var myCanvas_chart = new Chart(ctx).Bar(data, options)...

I got a white blank sheet. What's wrong?

**Comment by Jora-zolotoj** [comment]
@section scripts{
... src="~/Scripts/Chart.js">
</script>}
![123](https://cloud.githubusercontent.com/assets/23022812/19635535/7e847736-99dc-11e6-87bc-b3c5bf7e36f0.jpg)

**Comment by Jora-zolotoj** [comment]
bundles.Add(new ScriptBundle("~/bundles/site").Include(
          "~/Scripts/Chart.js"));

**Comment by Jora-zolotoj** [comment]
I do not know where to dig?

**Comment by martinobordin** [comment]
Be sure to have loaded the the chart.js library (check network tab in f12 developer tools)
