### ISSUE TITLE
Chart-Options are Ignored

### ISSUE THREAD

**Issue by SonicTTH** [martinobordin/Chart.Mvc#33]
Hello,

If I do this:

`           var barChart = new BarChart();
            barChart.ChartConfiguration.ScaleBeginAtZero = true;
            barChart.ChartConfiguration.ScaleOverride = true;
            barChart.ChartConfiguration.MaintainAspectRatio = false;`

The Scale doesnt begin by Zero. It begins with nearly the smallest of all the values which is practically really a questionable way of using charts. I'm headed over to the chart.js people to ask why thats the default.

But for now, the option isnt applied. I have to insert a Value of 0 for having an invisible column that makes the chart start at 0. Since that makes all the actually visible bars move to the left, its not that well of a problem solve, too, because now theres a blank space next to all of them all the time, like in the attached item.

![blank_space](https://cloud.githubusercontent.com/assets/3049818/20482227/cec47dac-afeb-11e6-9c22-cd607e36c147.png)

**Comment by VisualBean** [comment]
I'm also seeing this. None of my options are added when using chart v2

**Comment by martinobordin** [comment]
Only Chart v1 is supported
