### ISSUE TITLE
prefix/suffix of labels

### ISSUE THREAD

**Issue by VisualBean** [martinobordin/Chart.Mvc#34]
How would I prefix/suffix y-axis labels?
In JS it would be something like 
```
var options = {
            scaleLabel: function(valuePayload) {
                return "  " + Number(valuePayload.value + ' TB';
            }
```

**Comment by martinobordin** [comment]
Are you using chart.js v1 or v2?

_Martino Bordin_
_IT Consultant - Software Architect_

_mobile:_ +39 348 0136512
_skype:_ martino.bordin
_mail:_ info@martinobordin.it
_web:_ www.martinobordin.it

**Comment by VisualBean** [comment]
I'm using the one in the nuget package - 1.0.1.
Should i migrate to 2 instead?

**Comment by martinobordin** [comment]
Could you point me to the documentation of chart.js where it allows to
specify this configuration?

_Martino Bordin_
_IT Consultant - Software Architect_

_mobile:_ +39 348 0136512
_skype:_ martino.bordin
_mail:_ info@martinobordin.it
_web:_ www.martinobordin.it

**Comment by VisualBean** [comment]
http://www.chartjs.org/docs/#scales
in the scales part - look at Scale Title Configuration

**Comment by martinobordin** [comment]
My Chart.Mvc package is using Chart.js v1...so you have to look to this
documentation: https://github.com/chartjs/Chart.js/tree/v1.1.1/docs

_Martino Bordin_
_IT Consultant - Software Architect_

_mobile:_ +39 348 0136512
_skype:_ martino.bordin
_mail:_ info@martinobordin.it
_web:_ www.martinobordin.it
