### ISSUE TITLE
ComplexDataset.Label property not showed

### ISSUE THREAD

**Issue by stefanocasti** [martinobordin/Chart.Mvc#36]
Hi Martino,
why Label property doesn't show the text ("Data1") but empty string ?
This is the code:
 new ComplexDataset
                                  {
                                      Data = Datalist1,
                                      Label = "Data1",
                                      FillColor = "rgba(255, 206, 86, 0.2)",
                                      StrokeColor = "rgba(220,220,220,1)",
                                      PointColor = "rgba(220,220,220,1)",
                                      PointStrokeColor = "#fff",
                                      PointHighlightFill = "#fff",
                                      PointHighlightStroke = "rgba(220,220,220,1)",

Thanks in advance

**Comment by martinobordin** [comment]
Checkout the html source and see if the javascript written by chart.mvc is correc, according with chart.js v1 specifications

**Comment by stefanocasti** [comment]
I think it is, that's the javascript written:

<script type="text/javascript">var ctx = document.getElementById("ChartCanvas").getContext("2d");var data = JSON.parse('{"labels":["Cagliari","Vittorio Emanuele","Modena"],"datasets":[{"label":"Data1","fillColor":"rgba(255,206,86,0.2)","strokeColor":"rgba(220,220,220,1)","pointColor":"rgba(220,220,220,1)","pointStrokeColor":"#fff","pointHighlightFill":"#fff","pointHighlightStroke":"rgba(220,220,220,1)","data":[3.0,5.0,10.0]},{"label":"Data2","fillColor":"rgba(151,187,205,0.2)","strokeColor":"rgba(220,220,220,1)","pointColor":"rgba(151,187,205,1)","pointStrokeColor":"#fff","pointHighlightFill":"#fff","pointHighlightStroke":"rgba(151,187,205,1)","data":[3.0,3.0,3.0]},{"label":"Data3","fillColor":"rgba(102,204,0,0.2)","strokeColor":"rgba(220,220,220,1)","pointColor":"rgba(220,220,220,1)","pointStrokeColor":"#fff","pointHighlightFill":"#fff","pointHighlightStroke":"rgba(220,220,220,1)","data":[2.0,4.0,6.0]}]}');var options = JSON.parse('{"responsive":true}');var ChartCanvas_chart = new Chart(ctx).Bar(data, options)</script>

It seems the same behavior that you have on your site:
http://www.martinobordin.it/Chart.Mvc/Home/ComplexCharts

**Comment by stefanocasti** [comment]
I think it is, that's the javascript written:
<script type="text/javascript">var ctx = document.getElementById("ChartCanvas").getContext("2d");var data = JSON.parse('{"labels":["Cagliari","Vittorio Emanuele","Modena"],"datasets":[{"label":"Data1","fillColor":"rgba(255,206,86,0.2)","strokeColor":"rgba(220,220,220,1)","pointColor":"rgba(220,220,220,1)","pointStrokeColor":"#fff","pointHighlightFill":"#fff","pointHighlightStroke":"rgba(220,220,220,1)","data":[3.0,5.0,10.0]},{"label":"Data2","fillColor":"rgba(151,187,205,0.2)","strokeColor":"rgba(220,220,220,1)","pointColor":"rgba(151,187,205,1)","pointStrokeColor":"#fff","pointHighlightFill":"#fff","pointHighlightStroke":"rgba(151,187,205,1)","data":[3.0,3.0,3.0]},{"label":"Data3","fillColor":"rgba(102,204,0,0.2)","strokeColor":"rgba(220,220,220,1)","pointColor":"rgba(220,220,220,1)","pointStrokeColor":"#fff","pointHighlightFill":"#fff","pointHighlightStroke":"rgba(220,220,220,1)","data":[2.0,4.0,6.0]}]}');var options = JSON.parse('{"responsive":true}');var ChartCanvas_chart = new Chart(ctx).Bar(data, options)</script>

It seems the same behavior that you have on your site:
http://www.martinobordin.it/Chart.Mvc/Home/ComplexCharts

**Comment by martinobordin** [comment]
It's how chart.js v1 works.

Try this [sample ](https://github.com/chartjs/Chart.js/blob/v1.1.1/docs/02-Bar-Chart.md)in their documentation:
