### ISSUE TITLE
Facing issue to load chart

### ISSUE THREAD

**Issue by vijayanimje** [martinobordin/Chart.Mvc#40]
Hi,
I am trying  to implement charts in MVC4. Following error get thrown at runtime

![image](https://cloud.githubusercontent.com/assets/6419317/22562163/6c15fa40-e949-11e6-807c-a35a377d0fc4.png)

This line of code get generated in dll which is giving error
![image](https://cloud.githubusercontent.com/assets/6419317/22562388/533dd712-e94a-11e6-97d0-78a3bf214cbf.png)
***************************************************************************************
I have seen following difference in extension file. 
1. In sample file Extension.cs file has following code in bold which works file. 
private static MvcHtmlString CreateChart(string canvasId, string chartType, string jsonData, string jsonOptions)
        {
            var tag = new TagBuilder("script");
            tag.Attributes.Add("type", "text/javascript");
            var stringBuilder = new StringBuilder();
            stringBuilder.AppendFormat("var ctx = document.getElementById(\"{0}\").getContext(\"2d\");", canvasId);
            stringBuilder.AppendFormat("var data = JSON.parse('{0}');", jsonData);
            stringBuilder.AppendFormat("var options = JSON.parse('{0}');", jsonOptions);
            _**stringBuilder.Append("var " + canvasId + "_chart = new Chart(ctx, { type:'" + chartType.ToCamelCase() + "', data: data, options: options });");**_
            tag.InnerHtml = stringBuilder.ToString();
            return new MvcHtmlString(tag.ToString());
        }

2. But in downloaded nuget package extension dll has following code which gives error. 
![image](https://cloud.githubusercontent.com/assets/6419317/22563026/fa4cf5e0-e94c-11e6-8ed2-c6427cbdb07f.png)

Could you please update nuget package?

**Comment by martinobordin** [comment]
Be sure to have the refence to **Chart.js V1 (not v2)**

**Comment by vijayanimje** [comment]
yes. Its version 1.0.1

**Comment by vijayanimje** [comment]
Thanks. Its working fine. I installed nuget package again and it worked.

**Comment by martinobordin** [comment]
Check the sample then. And be sure to include the js before call the library

Inviato da iPhone
