### ISSUE TITLE
ASP MVC 5 and Graph Vertex Edge rendering

### ISSUE THREAD

**Issue by mach37** [martinobordin/Chart.Mvc#41]
Hi does this support graphs with edges and nodes

**Comment by martinobordin** [comment]
Could you explain better?

*Martino Bordin*
*IT Consultant - Software Architect*

*mobile:* +39 348 0136512
*skype:* martino.bordin
*mail:* info@martinobordin.it
*web:* www.martinobordin.it

**Comment by mach37** [comment]
In some of their samples they draw mesh like graphs, and I wanted to see if I can draw a small network with this

**Comment by martinobordin** [comment]
Can you share a link of those samples?

*Martino Bordin*
*IT Consultant - Software Architect*

*mobile:* +39 348 0136512
*skype:* martino.bordin
*mail:* info@martinobordin.it
*web:* www.martinobordin.it

**Comment by mach37** [comment]
Here is a link to the [ open source lib](http://bit.ly/2mQQjoa) I am trying to send the vertex and edges

**Comment by martinobordin** [comment]
That's another library..it's not chart.js
