### ISSUE TITLE
Issue with overriding scaling

### ISSUE THREAD

**Issue by SDmorgan** [martinobordin/Chart.Mvc#44]
lineChartBottom.ChartConfiguration.ScaleBeginAtZero = true;
    lineChartBottom.ChartConfiguration.ScaleOverride = true;
    lineChartBottom.ChartConfiguration.ScaleStartValue = 300;
    lineChartBottom.ChartConfiguration.ScaleSteps = 5;

The scaling basically starts at 300, each 5 steps show the value of 300.

Any suggestions would be appreciated.

**Comment by martinobordin** [comment]
Did you try with plain ChartJs v1?
