### ISSUE TITLE
Issue forking project , missing project error

### ISSUE THREAD

**Issue by prmces** [martinobordin/Chart.Mvc#45]
I dont know if this is an issue, but I tried to fork the last release version and there is a lot of deletes file.

Only the sample project is available.

I checkout two commits before and I have the "right" data.

I am looking for adding a title for the chart.

**Comment by martinobordin** [comment]
only chartjs v1 is supported right now.
Check the code here: https://github.com/martinobordin/Chart.Mvc/tree/V1
