### ISSUE TITLE
need help with generateLegend()

### ISSUE THREAD

**Issue by mokarenlam** [martinobordin/Chart.Mvc#46]
Hello,
I'm trying to display label/legend.  In LineChart.cshtml, I added generateLegend() like so:
- - - -
@{
    const string Canvas = "LineChart";
    var complexChart = new LineChart();
    complexChart.ComplexData.Labels.AddRange(FakeComplexChartDataLineChart.Labels);
    complexChart.ComplexData.Datasets.AddRange(FakeComplexChartDataLineChart.Datasets);
 }
<h3>@Canvas</h3>
<canvas id="@Canvas" width="400" height="400"></canvas>
<div id="legend" class="row chart-legend"></div>
@Html.CreateChart(Canvas, complexChart)
Canvas_chart.generateLegend();
- - - -

But still don't see the legend.  Can you correct my syntax?

**Comment by martinobordin** [comment]
generateLegend() is a javascript method..do you use it inside a <script> tag?
