### ISSUE TITLE
Reference to type 'HtmlString' claims it is defined in 'System.Web', but it could not be found.

### ISSUE THREAD

**Issue by zkhaleqi** [martinobordin/Chart.Mvc#52]
I cloned the solution, and changed Chart.MVC project from .NET to .NET Core 3.0. When trying to build the project I get the error mentioned as title of the Issue.

**Comment by Michal-Sitarz** [comment]
I tried to run it on .NET Core 2.2 and I have a similar issue. It looks like System.Web doesn't have a reference to .Mvc, so the html helper Html.CreateChart() does not exist.
I don't think that this library supports .Net Core :/ It's time to switch to the original Charts.JS now... It's a shame, it was a very nice and useful wrapper!

**Comment by martinobordin** [comment]
Hello.
Net core is not supported at the moment.
*Martino*

**Comment by cbs-cbt** [comment]
Hello,
For information, a GitHub project exists with the core version of this:
[Gareth Lewis / Chart.Mvc.Core · GitLab](https://gitlab.com/gareth.lewis91/chart.mvc.core)
