### ISSUE TITLE
BarChart() , ComplexDataset and Html.CreateChart not found

### ISSUE THREAD

**Issue by SimonJMBrown** [martinobordin/Chart.Mvc#54]
Apologies if being stupid here, fairly new to MVC with views...

I installed your wrapper to project in VS2017 from nuget manager.
I see you include chart.js so didn't add that as well (also tried installing Chart.js package as well with same result).

I have added bundle for the Chart.js and include in HEAD of cshtml. Added bundle to the BundleConfig
`    @Scripts.Render("~/bundles/ChartJS")`

I dragged in sample code from your "how do I use it?" section on site.

VS is telling me new BarChart() type or namespace not found
VS is telling me ComplexDataset type or namespace not found
VS is telling me @Html.CreateChart htmlHelper does not have a definition for CreateChart

Project is ASP.NET mvc against .net framework 4.6.1
Dependencies are later than required in your nuget description

I do have 
using System.Web.Helpers 

I can see Chart.Mvc in project references

I did implement a view with Microsoft's built in Chart but trying Chart.js as appears more feature rich and (thought) easier to implement.

I tried adding below but VS says unnecessary 
using Chart.Mvc

re-read documentation and tried multiple remove/installs/project clean etc but can't get past this.

**Comment by martinobordin** [comment]
Hi,
check also the <namespaces> section of this file: https://github.com/martinobordin/Chart.Mvc/blob/master/Chart.Mvc/Chart.Mvc.Sample/Views/Web.config

This act like a global using for your project. You should see the methods once done.

**Comment by SimonJMBrown** [comment]
Hi,

Had none of the `<sectionGroup name="system.web.webPages.razor"` or the `<system.web.webPages.razor>` sections in my web.config.

Not sure why not there?

Added sections (had to remove ..mvc.Sample... ) and now compiles and shows sample graph in debug mode
VS shows warning still;
![image](https://user-images.githubusercontent.com/43886998/121711374-72a08f00-cad2-11eb-8db2-a707eba82eeb.png)

Now to work out how to use BarChart to refer to my model lists :)

Thanks for quick response.

**Comment by SimonJMBrown** [comment]
I must be on Friday blues
Cannot for life of me work out how to set pie chart options...
have
` var pieChart = new PieChart();`
but no constructor or property allows me to add PieChartOptions

Checked sample project which has SimpleData option only and ChartConfiguration property is read only.

Can display data passing Data.Addrange from a List<SimpleData> and show basic pie but no customisation
