### ISSUE TITLE
Chart.Mvc namespace issue on razor page

### ISSUE THREAD

**Issue by onecentlin** [martinobordin/Chart.Mvc#6]
![image20150402_003](https://cloud.githubusercontent.com/assets/7122270/6956430/9c8b0fe8-d920-11e4-96bf-3e95bf6e26ce.png)

It seems namespace conflict with System.Web.Helpers.Chart and Chart.Mvc on razor page

I have to change the namespace to ChartJs.Mvc and recomplie the project to make my mvc project work. (my project is built in .NET Framework 4.5)

**Comment by martinobordin** [comment]
I don't think this is an actual issue. If you are using both chart libraries you would need to use the fully qualified namespace.
