### ISSUE TITLE
Unable to access specific chart options from ChartConfiguration

### ISSUE THREAD

**Issue by BelindaAtDimmi** [martinobordin/Chart.Mvc#7]
Because the ChartConfiguration of a chart is either SimpleChartOptions or ComplexChartOptions (and not the underlying options of the chart itself) I am unable to access particular settings. For example a DoughnutChart has PercentageInnerCutout in DoughnutChartOptions (which inherits SimpleChartOptions). I am unable to set that setting to anything other than its default. This is the same for any options specific to a chart.

**Comment by martinobordin** [comment]
Of course you can cast the ChartConfiguration to the specific chart options. However, I just published (even in Nuget) a better solution, that provides you the specific type of the chart options.
