### ISSUE TITLE
Why is ScaleLabel commented out?

### ISSUE THREAD

**Issue by robcube** [martinobordin/Chart.Mvc#8]
I see a commented out ScaleLabel in GlobalChartOptions.cs. I forked it, added back in and it ran fine. Is there any reason why it was left out?

**Comment by martinobordin** [comment]
No particular reasons..are you using it already?I can remove the comment and update the nuget package if you want

**Comment by robcube** [comment]
Yes using it already. No biggie, if no one else wonders like me, then just leave it be. Appreciate you making the project all the same! Saved me some time and helped with the learning curve.
